modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="autotech" #mandatory
version="${file.jarVersion}"
displayName="AutoTech"
logoFile="examplemod.png" #optional
credits="Thanks for this mod goes to samy7200 for textures"
authors="binary404" #optional
description='''
'''
[[dependencies.autotech]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.autotech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
